import { PROJECTION_TABLE, type LeagueProjection, type ProjectionRow } from "./projectionTable";

export interface PreseasonOdds {
  seasonSize: number;
  expectedPoints: number;
  winPct: number;
  top4Pct: number;
  top6Pct: number;
  top10Pct: number;
  relegationPct: number;
  projectedFinish: number;
}

/** League used when the caller doesn't know which league the season is in (or it isn't one of the
    five real ones): the Premier League — the default league and the most common pick. */
const FALLBACK_LEAGUE_ID = "league-gb1";

function leagueTable(leagueId: string | undefined): LeagueProjection {
  return (leagueId && PROJECTION_TABLE[leagueId]) || PROJECTION_TABLE[FALLBACK_LEAGUE_ID] || Object.values(PROJECTION_TABLE)[0]!;
}

/** Linear interpolation between the two table rows around `overall`, clamped to the table's range. */
function interpolate(rows: ProjectionRow[], overall: number): ProjectionRow {
  const first = rows[0]!;
  const last = rows[rows.length - 1]!;
  if (overall <= first.overall) return first;
  if (overall >= last.overall) return last;
  const hi = rows.findIndex((r) => r.overall >= overall);
  const a = rows[hi - 1]!;
  const b = rows[hi]!;
  const t = (overall - a.overall) / (b.overall - a.overall);
  const mix = (k: keyof ProjectionRow) => a[k] + (b[k] - a[k]) * t;
  return {
    overall,
    points: mix("points"),
    finish: mix("finish"),
    win: mix("win"),
    top4: mix("top4"),
    top6: mix("top6"),
    top10: mix("top10"),
    relegation: mix("relegation"),
  };
}

/** A whole percentage for display. 0 only when the simulations never once saw it happen, and capped
    at 99 — a long shot that did come off now and then reads "1%", never a flat "impossible", and
    nothing is ever shown as a certainty. */
function pct(value: number): number {
  if (value <= 0) return 0;
  return Math.max(1, Math.min(99, Math.round(value)));
}

/**
 * Pre-season projection shown on the draft confirm screen, read from a table generated by simulating
 * thousands of real seasons (tools/sim-lab/src/calibrate.ts → lib/projectionTable.ts): a user XI of
 * a given overall, dropped into the chosen league's real current field, playing the same engine,
 * AI-fill and fitness rules the live season uses. So "projected 4th, 74 pts" is what that squad
 * actually tends to do, not a hand-tuned curve (the old curve projected an Overall-90 XI to 89 pts
 * while champions were finishing on ~69). Every number comes from the same simulated seasons, so
 * win ≤ top 4 ≤ top 6 ≤ top 10 holds by construction.
 *
 * Also reused by lib/seasonNarrative.ts's verdict when a world predates the stored projection.
 */
export function computePreseasonOdds(overallRating: number, leagueId?: string): PreseasonOdds {
  const league = leagueTable(leagueId);
  const row = interpolate(league.rows, overallRating);
  const win = pct(row.win);
  const top4 = Math.max(win, pct(row.top4));
  const top6 = Math.max(top4, pct(row.top6));
  const top10 = Math.max(top6, pct(row.top10));
  return {
    seasonSize: league.clubs,
    expectedPoints: Math.round(row.points),
    winPct: win,
    top4Pct: top4,
    top6Pct: top6,
    top10Pct: top10,
    relegationPct: pct(row.relegation),
    projectedFinish: Math.max(1, Math.min(league.clubs, Math.round(row.finish))),
  };
}
