// GENERATED by tools/sim-lab/src/calibrate.ts --write — do not edit by hand. Re-run it after
// changing the engine, the OVR curve or the dataset so projections keep matching real simulations.
// Each row: a user XI of that overall replacing one AI club in the league's real current field,
// averaged over many simulated seasons — expected points, mean finish, and the % of seasons that
// ended 1st / top 4 / top 6 / top 10 / relegated.

export interface ProjectionRow {
  overall: number;
  points: number;
  finish: number;
  win: number;
  top4: number;
  top6: number;
  top10: number;
  relegation: number;
}

export interface LeagueProjection {
  name: string;
  clubs: number;
  rows: ProjectionRow[];
}

export const PROJECTION_TABLE: Record<string, LeagueProjection> = {
  "league-gb1": {
    name: "Premier League",
    clubs: 20,
    rows: [
      {overall: 62, points: 2.4, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 3.8, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 5.9, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 68, points: 8.9, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 70, points: 12.8, finish: 19.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 72, points: 17.3, finish: 19.7, win: 0, top4: 0, top6: 0, top10: 0, relegation: 98.5},
      {overall: 74, points: 22.2, finish: 19.3, win: 0, top4: 0, top6: 0, top10: 0, relegation: 93.5},
      {overall: 76, points: 29, finish: 18.2, win: 0, top4: 0, top6: 0.3, top10: 0.8, relegation: 74.3},
      {overall: 78, points: 37.7, finish: 16.2, win: 0, top4: 0.3, top6: 1.5, top10: 6, relegation: 40.8},
      {overall: 80, points: 45.2, finish: 13.8, win: 0, top4: 1.8, top6: 6.3, top10: 20.8, relegation: 16.8},
      {overall: 82, points: 53.2, finish: 10.3, win: 2.3, top4: 16.5, top6: 28.8, top10: 50.5, relegation: 6.8},
      {overall: 84, points: 62.5, finish: 6.2, win: 8, top4: 44, top6: 63.5, top10: 83.8, relegation: 1.5},
      {overall: 86, points: 69.2, finish: 3.8, win: 22.8, top4: 67, top6: 84.5, top10: 98.5, relegation: 0},
      {overall: 88, points: 76, finish: 2.4, win: 51.3, top4: 85.5, top6: 94.5, top10: 99.8, relegation: 0},
      {overall: 90, points: 83.2, finish: 1.4, win: 77.5, top4: 97.3, top6: 99.8, top10: 100, relegation: 0},
      {overall: 92, points: 88.5, finish: 1.1, win: 90.8, top4: 99.8, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 94.6, finish: 1, win: 100, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-es1": {
    name: "LaLiga",
    clubs: 20,
    rows: [
      {overall: 62, points: 5.5, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 9.2, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 14, finish: 19.8, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.5},
      {overall: 68, points: 19.8, finish: 19.4, win: 0, top4: 0, top6: 0, top10: 0, relegation: 92.8},
      {overall: 70, points: 26.9, finish: 18.4, win: 0, top4: 0, top6: 0, top10: 0.8, relegation: 74.8},
      {overall: 72, points: 34.9, finish: 16.4, win: 0, top4: 0.3, top6: 1.6, top10: 6.3, relegation: 47},
      {overall: 74, points: 42.9, finish: 13.8, win: 0, top4: 1, top6: 4.9, top10: 20.8, relegation: 19.3},
      {overall: 76, points: 51.1, finish: 10.8, win: 0.3, top4: 6.5, top6: 17.1, top10: 48, relegation: 4.8},
      {overall: 78, points: 59.9, finish: 7.6, win: 0.8, top4: 22, top6: 46.1, top10: 79.5, relegation: 1},
      {overall: 80, points: 67.6, finish: 5.3, win: 2, top4: 45.5, top6: 75.8, top10: 96.3, relegation: 0},
      {overall: 82, points: 75.5, finish: 3.7, win: 14.9, top4: 71.5, top6: 92, top10: 99.5, relegation: 0},
      {overall: 84, points: 83.2, finish: 2.4, win: 37.6, top4: 90.8, top6: 98.5, top10: 100, relegation: 0},
      {overall: 86, points: 88, finish: 1.7, win: 56.1, top4: 98, top6: 100, top10: 100, relegation: 0},
      {overall: 88, points: 92.7, finish: 1.4, win: 74.9, top4: 99.5, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 97.4, finish: 1.1, win: 90.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 100.7, finish: 1, win: 96, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 103.8, finish: 1, win: 99, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-it1": {
    name: "Serie A",
    clubs: 20,
    rows: [
      {overall: 62, points: 5.2, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 8.8, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 13.2, finish: 19.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.3},
      {overall: 68, points: 18.7, finish: 19.5, win: 0, top4: 0, top6: 0, top10: 0, relegation: 94.3},
      {overall: 70, points: 25.1, finish: 18.5, win: 0, top4: 0, top6: 0, top10: 0, relegation: 77},
      {overall: 72, points: 32.4, finish: 16.7, win: 0, top4: 0, top6: 0, top10: 3.3, relegation: 47.8},
      {overall: 74, points: 40.5, finish: 14.2, win: 0, top4: 0, top6: 0, top10: 16.3, relegation: 20.5},
      {overall: 76, points: 49.7, finish: 11.3, win: 0, top4: 1.8, top6: 4.8, top10: 44, relegation: 5},
      {overall: 78, points: 58.4, finish: 8.7, win: 0.3, top4: 7.5, top6: 19.8, top10: 75.8, relegation: 0.3},
      {overall: 80, points: 65.1, finish: 6.8, win: 1.5, top4: 20.5, top6: 44.8, top10: 93.3, relegation: 0},
      {overall: 82, points: 73, finish: 4.8, win: 14.5, top4: 48.8, top6: 73.5, top10: 98.5, relegation: 0},
      {overall: 84, points: 81.4, finish: 2.8, win: 38.5, top4: 80.8, top6: 92.3, top10: 100, relegation: 0},
      {overall: 86, points: 86.6, finish: 1.8, win: 58.8, top4: 95, top6: 97.8, top10: 100, relegation: 0},
      {overall: 88, points: 91.2, finish: 1.4, win: 77.8, top4: 98, top6: 99.3, top10: 100, relegation: 0},
      {overall: 90, points: 95.9, finish: 1.1, win: 92.5, top4: 99.8, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 99.5, finish: 1, win: 97.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 103.1, finish: 1, win: 98, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-l1": {
    name: "Bundesliga",
    clubs: 18,
    rows: [
      {overall: 62, points: 4.4, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 7.8, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.8},
      {overall: 66, points: 11.6, finish: 17.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.3},
      {overall: 68, points: 16.7, finish: 17.5, win: 0, top4: 0, top6: 0, top10: 0, relegation: 94.8},
      {overall: 70, points: 22.9, finish: 16.6, win: 0, top4: 0, top6: 0, top10: 0.3, relegation: 77.8},
      {overall: 72, points: 29.4, finish: 15.2, win: 0, top4: 0, top6: 0.3, top10: 4, relegation: 50.5},
      {overall: 74, points: 36.2, finish: 13.2, win: 0, top4: 0.8, top6: 3, top10: 17.5, relegation: 24.8},
      {overall: 76, points: 44.9, finish: 10.4, win: 0.4, top4: 6.8, top6: 16.8, top10: 46.3, relegation: 7.5},
      {overall: 78, points: 53.9, finish: 7.4, win: 1.1, top4: 22.3, top6: 44, top10: 79.5, relegation: 0.8},
      {overall: 80, points: 60.8, finish: 5.1, win: 6.4, top4: 46.3, top6: 71.5, top10: 96.8, relegation: 0},
      {overall: 82, points: 67.6, finish: 3.3, win: 24.6, top4: 73.8, top6: 89.5, top10: 99.8, relegation: 0},
      {overall: 84, points: 74.4, finish: 2, win: 51, top4: 93.3, top6: 98, top10: 100, relegation: 0},
      {overall: 86, points: 79.1, finish: 1.4, win: 71.8, top4: 99.3, top6: 100, top10: 100, relegation: 0},
      {overall: 88, points: 82.8, finish: 1.2, win: 85.3, top4: 99.8, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 86.8, finish: 1.1, win: 94.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 90.2, finish: 1, win: 98.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 93.5, finish: 1, win: 100, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-fr1": {
    name: "Ligue 1",
    clubs: 18,
    rows: [
      {overall: 62, points: 4.4, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 8.1, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 12.1, finish: 17.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.8},
      {overall: 68, points: 17.1, finish: 17.6, win: 0, top4: 0, top6: 0, top10: 0, relegation: 95.5},
      {overall: 70, points: 23.9, finish: 16.6, win: 0, top4: 0, top6: 0, top10: 1.5, relegation: 79},
      {overall: 72, points: 30.8, finish: 14.9, win: 0, top4: 0, top6: 0.3, top10: 8.5, relegation: 53},
      {overall: 74, points: 37.8, finish: 12.7, win: 0, top4: 1.5, top6: 4, top10: 28, relegation: 27.5},
      {overall: 76, points: 46.5, finish: 9.6, win: 0.3, top4: 10.3, top6: 20.8, top10: 60.3, relegation: 8},
      {overall: 78, points: 55, finish: 6.6, win: 2, top4: 28.8, top6: 49.5, top10: 87.8, relegation: 0.3},
      {overall: 80, points: 61.4, finish: 4.7, win: 6.8, top4: 53.8, top6: 75.8, top10: 98.3, relegation: 0},
      {overall: 82, points: 68, finish: 3.1, win: 21.3, top4: 79.5, top6: 92.5, top10: 99.8, relegation: 0},
      {overall: 84, points: 74.8, finish: 2, win: 43.5, top4: 95.3, top6: 99.3, top10: 100, relegation: 0},
      {overall: 86, points: 79.5, finish: 1.5, win: 62.5, top4: 99.3, top6: 100, top10: 100, relegation: 0},
      {overall: 88, points: 83.3, finish: 1.2, win: 79.5, top4: 99.8, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 87.2, finish: 1.1, win: 91.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 90.3, finish: 1, win: 95.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 93.8, finish: 1, win: 100, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
};
