// GENERATED by tools/sim-lab/src/calibrate.ts --write — do not edit by hand. Re-run it after
// changing the engine, the OVR curve or the dataset so projections keep matching real simulations.
// Each row: a user XI of that overall replacing one AI club in the league's real current field,
// averaged over many simulated seasons — expected points, mean finish, and the % of seasons that
// ended 1st / top 4 / top 6 / top 10 / relegated.

export interface ProjectionRow {
  overall: number;
  points: number;
  finish: number;
  win: number;
  top4: number;
  top6: number;
  top10: number;
  relegation: number;
}

export interface LeagueProjection {
  name: string;
  clubs: number;
  rows: ProjectionRow[];
}

export const PROJECTION_TABLE: Record<string, LeagueProjection> = {
  "league-gb1": {
    name: "Premier League",
    clubs: 20,
    rows: [
      {overall: 62, points: 2.3, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 3.6, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 5.7, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 68, points: 9.1, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 70, points: 13.3, finish: 19.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.8},
      {overall: 72, points: 18.3, finish: 19.7, win: 0, top4: 0, top6: 0, top10: 0, relegation: 97.5},
      {overall: 74, points: 23.8, finish: 19.3, win: 0, top4: 0, top6: 0, top10: 0, relegation: 90.8},
      {overall: 76, points: 30.8, finish: 18.2, win: 0, top4: 0.3, top6: 0.3, top10: 1, relegation: 73},
      {overall: 78, points: 39.1, finish: 16, win: 0, top4: 1.3, top6: 2.5, top10: 9.3, relegation: 45},
      {overall: 80, points: 47.5, finish: 12.8, win: 1.3, top4: 6, top6: 11.8, top10: 31, relegation: 20.3},
      {overall: 82, points: 55.9, finish: 8.9, win: 5.8, top4: 23.3, top6: 36, top10: 62.8, relegation: 5.5},
      {overall: 84, points: 64.6, finish: 5.2, win: 16, top4: 54.8, top6: 69.3, top10: 89.5, relegation: 0.3},
      {overall: 86, points: 72.3, finish: 2.8, win: 36.5, top4: 83.5, top6: 91.5, top10: 99.5, relegation: 0},
      {overall: 88, points: 79.3, finish: 1.7, win: 63.3, top4: 96.3, top6: 98.8, top10: 100, relegation: 0},
      {overall: 90, points: 85, finish: 1.3, win: 83.5, top4: 99, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 89.4, finish: 1.1, win: 94, top4: 99.8, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 94.2, finish: 1, win: 100, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-es1": {
    name: "LaLiga",
    clubs: 20,
    rows: [
      {overall: 62, points: 5.8, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 9.3, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 14, finish: 19.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.3},
      {overall: 68, points: 19.6, finish: 19.6, win: 0, top4: 0, top6: 0, top10: 0, relegation: 96},
      {overall: 70, points: 26.2, finish: 18.7, win: 0, top4: 0, top6: 0, top10: 0.3, relegation: 83.3},
      {overall: 72, points: 34.2, finish: 16.7, win: 0, top4: 0, top6: 1, top10: 5, relegation: 55.5},
      {overall: 74, points: 43, finish: 13.7, win: 0, top4: 1, top6: 6.3, top10: 23.5, relegation: 24.5},
      {overall: 76, points: 51.4, finish: 10.4, win: 0, top4: 5.3, top6: 21.5, top10: 55.5, relegation: 6},
      {overall: 78, points: 59.5, finish: 7.5, win: 0, top4: 17, top6: 46.5, top10: 84.3, relegation: 0.5},
      {overall: 80, points: 67.2, finish: 5.4, win: 1.5, top4: 40.3, top6: 72, top10: 97.5, relegation: 0},
      {overall: 82, points: 75.1, finish: 3.8, win: 9, top4: 69.3, top6: 90.3, top10: 100, relegation: 0},
      {overall: 84, points: 82.4, finish: 2.6, win: 23.5, top4: 89.8, top6: 98.5, top10: 100, relegation: 0},
      {overall: 86, points: 88.2, finish: 1.9, win: 43.8, top4: 97.3, top6: 100, top10: 100, relegation: 0},
      {overall: 88, points: 93, finish: 1.4, win: 67, top4: 99.3, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 97, finish: 1.2, win: 84.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 100.1, finish: 1.1, win: 93.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 102.9, finish: 1, win: 98, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-it1": {
    name: "Serie A",
    clubs: 20,
    rows: [
      {overall: 62, points: 5.2, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 8.1, finish: 20, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 12.2, finish: 19.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.8},
      {overall: 68, points: 17.8, finish: 19.6, win: 0, top4: 0, top6: 0, top10: 0, relegation: 95.3},
      {overall: 70, points: 24.1, finish: 18.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 81.8},
      {overall: 72, points: 31.3, finish: 17.4, win: 0, top4: 0, top6: 0.3, top10: 2.8, relegation: 57},
      {overall: 74, points: 39.6, finish: 15, win: 0, top4: 0, top6: 1, top10: 14, relegation: 27},
      {overall: 76, points: 47.9, finish: 12.1, win: 0, top4: 0.3, top6: 4.5, top10: 39, relegation: 7.5},
      {overall: 78, points: 56.3, finish: 9.1, win: 0.5, top4: 6.3, top6: 20, top10: 70.8, relegation: 1.5},
      {overall: 80, points: 65, finish: 6.3, win: 4, top4: 28.5, top6: 50.8, top10: 91.8, relegation: 0.3},
      {overall: 82, points: 73.2, finish: 4, win: 20.8, top4: 60.8, top6: 80.5, top10: 98.8, relegation: 0},
      {overall: 84, points: 80.3, finish: 2.4, win: 50.5, top4: 84.5, top6: 95.5, top10: 100, relegation: 0},
      {overall: 86, points: 86.1, finish: 1.5, win: 74.3, top4: 96, top6: 99.5, top10: 100, relegation: 0},
      {overall: 88, points: 91.3, finish: 1.2, win: 87.8, top4: 99.8, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 95.6, finish: 1, win: 96.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 98.9, finish: 1, win: 99.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 102.1, finish: 1, win: 100, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-l1": {
    name: "Bundesliga",
    clubs: 18,
    rows: [
      {overall: 62, points: 4.1, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 6.8, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 66, points: 10.2, finish: 17.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.8},
      {overall: 68, points: 15.2, finish: 17.7, win: 0, top4: 0, top6: 0, top10: 0, relegation: 97.3},
      {overall: 70, points: 21.5, finish: 17, win: 0, top4: 0, top6: 0, top10: 0.8, relegation: 84.8},
      {overall: 72, points: 27.9, finish: 15.5, win: 0, top4: 0, top6: 0, top10: 4.8, relegation: 60.8},
      {overall: 74, points: 34.3, finish: 13.6, win: 0, top4: 0, top6: 1.5, top10: 17.8, relegation: 33.5},
      {overall: 76, points: 42.2, finish: 10.9, win: 0, top4: 2.3, top6: 11.3, top10: 45, relegation: 11.3},
      {overall: 78, points: 50.4, finish: 8.1, win: 0.5, top4: 13.3, top6: 35, top10: 76.3, relegation: 1.5},
      {overall: 80, points: 57.8, finish: 5.9, win: 3.3, top4: 36.5, top6: 64.5, top10: 94, relegation: 0.3},
      {overall: 82, points: 64.9, finish: 4.1, win: 12, top4: 64.3, top6: 85.8, top10: 98.8, relegation: 0},
      {overall: 84, points: 71.4, finish: 2.8, win: 30.8, top4: 85.8, top6: 95.8, top10: 99.8, relegation: 0},
      {overall: 86, points: 77.2, finish: 1.8, win: 56.3, top4: 97, top6: 99.3, top10: 100, relegation: 0},
      {overall: 88, points: 81.6, finish: 1.4, win: 76.3, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 84.6, finish: 1.2, win: 86.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 87.6, finish: 1.1, win: 93.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 90.3, finish: 1, win: 99, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
  "league-fr1": {
    name: "Ligue 1",
    clubs: 18,
    rows: [
      {overall: 62, points: 5.3, finish: 18, win: 0, top4: 0, top6: 0, top10: 0, relegation: 100},
      {overall: 64, points: 9.2, finish: 17.9, win: 0, top4: 0, top6: 0, top10: 0, relegation: 99.5},
      {overall: 66, points: 13.8, finish: 17.7, win: 0, top4: 0, top6: 0, top10: 0, relegation: 96.3},
      {overall: 68, points: 19.5, finish: 17.1, win: 0, top4: 0, top6: 0, top10: 0, relegation: 86.3},
      {overall: 70, points: 26.4, finish: 15.8, win: 0, top4: 0, top6: 0, top10: 1.8, relegation: 62.8},
      {overall: 72, points: 33.7, finish: 13.8, win: 0, top4: 0, top6: 0.8, top10: 12, relegation: 31.3},
      {overall: 74, points: 41.2, finish: 11.4, win: 0, top4: 1.5, top6: 7.5, top10: 38.5, relegation: 10},
      {overall: 76, points: 49.4, finish: 8.7, win: 0, top4: 10, top6: 27, top10: 71.5, relegation: 2},
      {overall: 78, points: 57.2, finish: 6.2, win: 1.8, top4: 32.3, top6: 57.3, top10: 91.8, relegation: 0},
      {overall: 80, points: 64.4, finish: 4.2, win: 11.5, top4: 61.3, top6: 84.5, top10: 98.5, relegation: 0},
      {overall: 82, points: 70.9, finish: 2.7, win: 31.3, top4: 83.3, top6: 97.3, top10: 100, relegation: 0},
      {overall: 84, points: 76.5, finish: 1.8, win: 53.3, top4: 95.8, top6: 99.8, top10: 100, relegation: 0},
      {overall: 86, points: 81.6, finish: 1.4, win: 73, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 88, points: 85.5, finish: 1.1, win: 88.5, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 90, points: 88.3, finish: 1, win: 96.1, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 92, points: 90.9, finish: 1, win: 98.1, top4: 100, top6: 100, top10: 100, relegation: 0},
      {overall: 94, points: 93.8, finish: 1, win: 98.5, top4: 100, top6: 100, top10: 100, relegation: 0},
    ],
  },
};
