/** Squad-tier flavor names (38-0 §9): maps a squad's overall rating to a narrative-flavor band,
    surfaced on the draft-complete screen, the results screen and the leaderboard tier filter. Reuses
    the app's existing accent palette (amber/mint/teal/plum/crimson, smoke for the neutral middle
    band) rather than inventing new tier-specific colors — same approach as positionColors.ts.

    The bands describe what such a squad actually does in the simulated leagues (lib/projectionTable.ts,
    generated by tools/sim-lab/src/calibrate.ts), so the name and the projection never disagree:
    88+ is the title favourite in every league, 85-87 a title contender, 82-84 fights for Europe,
    78-81 is mid-table, 74-77 battles relegation. On the 2026-10 rating curve a well-drafted XI
    (best available player every spin) has a median of ~81 with Season ratings and ~85 with Prime,
    so "Galácticos" is a genuinely rare outcome (top ~1% of Season-ratings drafts) rather than the
    label nearly every squad got when the old bands met the inflated old ratings. */

export type SquadTier = "Galácticos" | "Elite" | "Strong" | "Mid-table" | "Budget" | "Minnows";

const TIER_BANDS: { min: number; tier: SquadTier }[] = [
  { min: 88, tier: "Galácticos" },
  { min: 85, tier: "Elite" },
  { min: 82, tier: "Strong" },
  { min: 78, tier: "Mid-table" },
  { min: 74, tier: "Budget" },
  { min: 0, tier: "Minnows" },
];

export function squadTierName(overall: number): SquadTier {
  return TIER_BANDS.find((b) => overall >= b.min)!.tier;
}

export const TIER_TEXT: Record<SquadTier, string> = {
  Galácticos: "text-amber-300",
  Elite: "text-mint-300",
  Strong: "text-teal-300",
  "Mid-table": "text-smoke-300",
  Budget: "text-plum-300",
  Minnows: "text-crimson-300",
};

export const TIER_BORDER: Record<SquadTier, string> = {
  Galácticos: "border-amber-400/60",
  Elite: "border-mint-400/60",
  Strong: "border-teal-400/50",
  "Mid-table": "border-ink-600",
  Budget: "border-plum-400/50",
  Minnows: "border-crimson-400/50",
};
